version: '2.3'

services:
  microsoft_sqlserver:
    image: docker.elastic.co/integrations-ci/beats-mssql:${MSSQL_VERSION:-2017-GA-ubuntu}-1
    build:
      context: .
      args:
        MSSQL_VERSION: ${MSSQL_VERSION:-2017-GA-ubuntu}
    ports:
      - 1433
