---
description: Pipeline for processing mssql performance
processors:
- rename:
    field: sql
    target_field: mssql
    ignore_missing: true
    ignore_failure: true
on_failure:
- set:
    field: error.message
    value: "{{ _ingest.on_failure_message }}"
