version: '2.3'
services:
  mongodb:
    image: docker.elastic.co/integrations-ci/beats-mongodb:${MONGODB_VERSION:-5.0}
    user: mongodb
    build:
      context: .
      args:
        MONGODB_VERSION: ${MONGODB_VERSION:-5.0}
    command:
      - '--replSet'
      - 'beats'
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    ports:
      - 27017
    volumes:
      - ./setup.sh:/docker-entrypoint-initdb.d/setup.sh
      - ${SERVICE_LOGS_DIR}:/var/log/mongodb
