version: '2.3'
services:
  mongodb:
    tty: true
    image: docker.elastic.co/integrations-ci/beats-mongodb:${MONGODB_VERSION:-5.0}
    user: root
    build:
      context: .
      args:
        MONGODB_VERSION: ${MONGODB_VERSION:-5.0}
    ports:
      - 27017
    command:
      - '--replSet'
      - 'beats'
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
      - '--logappend'
      - '--bind_ip_all'
    volumes:
      - ./setup.sh:/docker-entrypoint-initdb.d/setup.sh
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
      - ${SERVICE_LOGS_DIR}:/var/log/mongodb
